### PR TITLE
Add migrations

### PR DESCRIPTION
**Pull request by d4be4st**
@infinum/rails-team please take a look

### CODE REVIEW

**Comment by PetarCurkovic** [comment]
Looks good 👍

**Comment by vrosancic** [comment]
👍

**Comment by melcha** [comment]
👍

**Comment by DamirSvrtan** [comment]
@d4be4st if we are using raw sql in migrations, for what do we need the `migration_data` gem?

How does this gem handle when data migrations don't go well (the up part goes, but the data doesn't)? How do you handle your migrations at that point, you clean up the schema migrations row on production and run it again?

I just want to see a benefit of using this gem :) It's also still not supporting Rails 5.

**Pull request merged**
